import { MenuPreview } from "./MenuPreview";
export function Hero() {
  return (
    <section className="hero">
      <div className="hero-copy">
        <p className="eyebrow">
          <span className="status-dot"></span>A little room for your eyes
        </p>
        <h1>
          Look away.
          <br />
          Come back fresh.
        </h1>
        <p className="lede">
          A quiet reminder to rest your eyes.
          <br />
          Right in your Mac’s menu bar.
        </p>
        <div className="hero-actions">
          <a className="btn" href="#download">
            <svg aria-hidden="true" className="icon">
              <use href="#arrow" />
            </svg>
            Get EyePause
          </a>
          <a className="text-link" href="#experience">
            See it in motion <span aria-hidden="true">↗</span>
          </a>
        </div>
        <p className="hero-note">Free for your Mac. Just for you.</p>
      </div>
      <div className="instrument">
        <div className="dial-label">YOUR NEXT MOMENT OF REST</div>
        <div
          className="dial"
          role="img"
          aria-label="Countdown dial, 14 minutes 32 seconds until your next break"
        >
          <svg viewBox="0 0 420 420">
            <circle
              cx="210"
              cy="210"
              r="172"
              fill="none"
              stroke="var(--border)"
              strokeWidth="1"
            />
            <line
              x1="210.00"
              y1="31.00"
              x2="210.00"
              y2="22.00"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="228.71"
              y1="31.98"
              x2="229.23"
              y2="27.01"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="247.22"
              y1="34.91"
              x2="248.26"
              y2="30.02"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="265.31"
              y1="39.76"
              x2="266.86"
              y2="35.01"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="282.81"
              y1="46.48"
              x2="284.84"
              y2="41.91"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="299.50"
              y1="54.98"
              x2="304.00"
              y2="47.19"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="315.21"
              y1="65.19"
              x2="318.15"
              y2="61.14"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="329.77"
              y1="76.98"
              x2="333.12"
              y2="73.26"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="343.02"
              y1="90.23"
              x2="346.74"
              y2="86.88"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="354.81"
              y1="104.79"
              x2="358.86"
              y2="101.85"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="365.02"
              y1="120.50"
              x2="372.81"
              y2="116.00"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="373.52"
              y1="137.19"
              x2="378.09"
              y2="135.16"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="380.24"
              y1="154.69"
              x2="384.99"
              y2="153.14"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="385.09"
              y1="172.78"
              x2="389.98"
              y2="171.74"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="388.02"
              y1="191.29"
              x2="392.99"
              y2="190.77"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="389.00"
              y1="210.00"
              x2="398.00"
              y2="210.00"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="388.02"
              y1="228.71"
              x2="392.99"
              y2="229.23"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="385.09"
              y1="247.22"
              x2="389.98"
              y2="248.26"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="380.24"
              y1="265.31"
              x2="384.99"
              y2="266.86"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="373.52"
              y1="282.81"
              x2="378.09"
              y2="284.84"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="365.02"
              y1="299.50"
              x2="372.81"
              y2="304.00"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="354.81"
              y1="315.21"
              x2="358.86"
              y2="318.15"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="343.02"
              y1="329.77"
              x2="346.74"
              y2="333.12"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="329.77"
              y1="343.02"
              x2="333.12"
              y2="346.74"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="315.21"
              y1="354.81"
              x2="318.15"
              y2="358.86"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="299.50"
              y1="365.02"
              x2="304.00"
              y2="372.81"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="282.81"
              y1="373.52"
              x2="284.84"
              y2="378.09"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="265.31"
              y1="380.24"
              x2="266.86"
              y2="384.99"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="247.22"
              y1="385.09"
              x2="248.26"
              y2="389.98"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="228.71"
              y1="388.02"
              x2="229.23"
              y2="392.99"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="210.00"
              y1="389.00"
              x2="210.00"
              y2="398.00"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="191.29"
              y1="388.02"
              x2="190.77"
              y2="392.99"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="172.78"
              y1="385.09"
              x2="171.74"
              y2="389.98"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="154.69"
              y1="380.24"
              x2="153.14"
              y2="384.99"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="137.19"
              y1="373.52"
              x2="135.16"
              y2="378.09"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="120.50"
              y1="365.02"
              x2="116.00"
              y2="372.81"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="104.79"
              y1="354.81"
              x2="101.85"
              y2="358.86"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="90.23"
              y1="343.02"
              x2="86.88"
              y2="346.74"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="76.98"
              y1="329.77"
              x2="73.26"
              y2="333.12"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="65.19"
              y1="315.21"
              x2="61.14"
              y2="318.15"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="54.98"
              y1="299.50"
              x2="47.19"
              y2="304.00"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="46.48"
              y1="282.81"
              x2="41.91"
              y2="284.84"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="39.76"
              y1="265.31"
              x2="35.01"
              y2="266.86"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="34.91"
              y1="247.22"
              x2="30.02"
              y2="248.26"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="31.98"
              y1="228.71"
              x2="27.01"
              y2="229.23"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="31.00"
              y1="210.00"
              x2="22.00"
              y2="210.00"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="31.98"
              y1="191.29"
              x2="27.01"
              y2="190.77"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="34.91"
              y1="172.78"
              x2="30.02"
              y2="171.74"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="39.76"
              y1="154.69"
              x2="35.01"
              y2="153.14"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="46.48"
              y1="137.19"
              x2="41.91"
              y2="135.16"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="54.98"
              y1="120.50"
              x2="47.19"
              y2="116.00"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="65.19"
              y1="104.79"
              x2="61.14"
              y2="101.85"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="76.98"
              y1="90.23"
              x2="73.26"
              y2="86.88"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="90.23"
              y1="76.98"
              x2="86.88"
              y2="73.26"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="104.79"
              y1="65.19"
              x2="101.85"
              y2="61.14"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="120.50"
              y1="54.98"
              x2="116.00"
              y2="47.19"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="137.19"
              y1="46.48"
              x2="135.16"
              y2="41.91"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="154.69"
              y1="39.76"
              x2="153.14"
              y2="35.01"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="172.78"
              y1="34.91"
              x2="171.74"
              y2="30.02"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <line
              x1="191.29"
              y1="31.98"
              x2="190.77"
              y2="27.01"
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            <circle
              cx="210"
              cy="210"
              r="143"
              fill="none"
              stroke="var(--border)"
              strokeWidth="3"
            />
            <circle
              cx="210"
              cy="210"
              r="143"
              fill="none"
              stroke="var(--accent)"
              strokeWidth="3"
              strokeDasharray="653 899"
              transform="rotate(-90 210 210)"
            />
            <circle cx="68.5" cy="232.4" r="5" fill="var(--accent-text)" />
            <text
              x="210"
              y="25"
              textAnchor="middle"
              fill="var(--fg-subtle)"
              fontSize="10"
              fontFamily="monospace"
            >
              20
            </text>
            <text
              x="402"
              y="214"
              textAnchor="middle"
              fill="var(--fg-subtle)"
              fontSize="10"
              fontFamily="monospace"
            >
              15
            </text>
            <text
              x="210"
              y="405"
              textAnchor="middle"
              fill="var(--fg-subtle)"
              fontSize="10"
              fontFamily="monospace"
            >
              10
            </text>
            <text
              x="19"
              y="214"
              textAnchor="middle"
              fill="var(--fg-subtle)"
              fontSize="10"
              fontFamily="monospace"
            >
              05
            </text>
          </svg>
          <div className="read">
            <span className="label">A little focus. Then a little rest.</span>
            <span className="time">14:32</span>
            <span className="sub">UNTIL YOUR NEXT BREAK</span>
          </div>
        </div>
        <MenuPreview />
        <p className="instrument-caption">
          <span>ALWAYS WITHIN REACH</span>A small presence.
          <br />A useful reminder.
        </p>
      </div>
    </section>
  );
}
